// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using remittance.api.Data;

namespace remittance.api.Migrations
{
    [DbContext(typeof(DatalayerContext))]
    [Migration("20210324144000_changed_branch_properties")]
    partial class changed_branch_properties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("remittance.api.Model.Branch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("baseCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("canReceiveFromMMT")
                        .HasColumnType("bit");

                    b.Property<bool>("canReceiveTMTFromPartner")
                        .HasColumnType("bit");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<bool?>("commDiscountApprovalIsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("commDiscountApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("commDiscountCpoApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("commDiscountParentApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("commForPayingBranch")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("commForPayingBranchStatus")
                        .HasColumnType("bit");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("createdby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdon")
                        .HasColumnType("datetime2");

                    b.Property<string>("domain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isPayee")
                        .HasColumnType("bit");

                    b.Property<int>("limit")
                        .HasColumnType("int");

                    b.Property<int?>("maxAmountApproval")
                        .HasColumnType("int");

                    b.Property<bool?>("maxAmountApprovalIsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("maxAmountApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("maxAmountCpoApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("maxAmountParentApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("maxCommApproval")
                        .HasColumnType("bit");

                    b.Property<bool?>("maxCommApprovalIsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("maxCommApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("maxCommCpoApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("maxCommParentApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("minCommApproval")
                        .HasColumnType("bit");

                    b.Property<bool?>("minCommApprovalIsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("minCommApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("minCommCpoApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("minCommParentApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("mmtCommForSending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("mmtCommForSendingStatus")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("parentBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenceBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("tmtCommForSending")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("tmtCommForSendingStatus")
                        .HasColumnType("bit");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
